#!/data/data/com.termux/files/usr/bin/bash
clear
sleep 0.5
#banner
printf "\e[1;3$(( $RANDOM * 6 / 32767 + 1 ))m"
echo '
        ooooooooooooo
     oooo/:-....-:/oooo
    ooo+- .-//+++/-. -+ooo
   ooo- -+oooooooooo+- -ooo
  ooo. /oo. .ooooooooo/ .ooo
 ooo/ -oo+  `+ooooooooo- /ooo
 ooo: /ooo: .+ooooooooo/ :ooo
 ooo/ -oooo+. .:/`.-+oo- /ooo
 oooo- /ooooo+:.`  .oo/ .oooo
 oooo/ -oooooooooooo+- -oooo
  ooo` ..``-//++//-``-+ooo
  ooo+-::/+/:-....-:/oooo
    ooo)oooooooooooo
      oooooooooo
       ooo
         oo)

'
#checking storage permission (allow)
if [ ! -d '/data/data/com.termux/files/home/storage' ];then
termux-setup-storage
sleep 5
fi

#checking dir
if [ ! -d '/storage/emulated/0/WhatsApp/Media/.Statuses' ];then
echo
echo -e '\033[1m[x] WhatsApp not installed, [↓] Install it, [!] Opening Play Store.' 
fi

if [ ! -d '/storage/emulated/0/DCIM' ];then
cd /sdcard
mkdir DCIM
fi

#checking dir
if [ ! -d '/storage/emulated/0/DCIM/WA-STATUS' ];then
cd /sdcard/DCIM
mkdir WA-STATUS
fi



#main activity
c1='\e[1;3$(( $RANDOM * 6 / 32767 + 1 ))m'
c2='\e[0;1;30m'
c3='\e[1m'
HIDCRSR(){ echo -en "\033[?25l";}
NORM(){ echo -en "\033[?12l\033[?25h";}

HIDCRSR
echo -ne "${c2}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬${c3} (0.1%) \r"
sleep 0.5
echo -ne "${c1}▬${c2}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬${c3} (0.2%) \r"
sleep 0.1
echo -ne "${c1}▬▬${c2}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬${c3} (0.3%) \r"
sleep 0.1
echo -ne "${c1}▬▬▬${c2}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬${c3} (0.4%) \r"
sleep 0.1
echo -ne "${c1}▬▬▬▬${c2}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬${c3} (0.6%) \r"
sleep 0.1
echo -ne "${c1}▬▬▬▬▬${c2}▬▬▬▬▬▬▬▬▬▬▬▬▬▬${c3} (0.8%) \r"
sleep 0.1
echo -ne "${c1}▬▬▬▬▬▬${c2}▬▬▬▬▬▬▬▬▬▬▬▬▬${c3} (01%)  \r"
sleep 0.1
echo -ne "${c1}▬▬▬▬▬▬▬${c2}▬▬▬▬▬▬▬▬▬▬▬▬${c3} (04%)  \r"
sleep 0.1
echo -ne "${c1}▬▬▬▬▬▬▬▬${c2}▬▬▬▬▬▬▬▬▬▬▬${c3} (08%)  \r"
sleep 0.1
echo -ne "${c1}▬▬▬▬▬▬▬▬▬${c2}▬▬▬▬▬▬▬▬▬▬${c3} (15%)  \r"
sleep 0.1
echo -ne "${c1}▬▬▬▬▬▬▬▬▬▬${c2}▬▬▬▬▬▬▬▬▬${c3} (25%)  \r"
sleep 0.1
echo -ne "${c1}▬▬▬▬▬▬▬▬▬▬▬${c2}▬▬▬▬▬▬▬▬${c3} (35%) \r"
sleep 0.1
echo -ne "${c1}▬▬▬▬▬▬▬▬▬▬▬▬${c2}▬▬▬▬▬▬▬${c3} (45%) \r"
sleep 0.1
echo -ne "${c1}▬▬▬▬▬▬▬▬▬▬▬▬▬${c2}▬▬▬▬▬▬${c3} (55%] \r"
sleep 0.1
echo -ne "${c1}▬▬▬▬▬▬▬▬▬▬▬▬▬▬${c2}▬▬▬▬▬${c3} (60%) \r"
sleep 0.1
echo -ne "${c1}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬${c2}▬▬▬▬${c3} (66%) \r"
sleep 0.1
echo -ne "${c1}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬${c2}▬▬▬${c3} (77%) \r"
sleep 0.1
echo -ne "${c1}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬${c2}▬▬${c3} (88%) \r"
sleep 0.1
echo -ne "${c1}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬${c2}▬${c3} (99%) \r"
sleep 0.1
echo -ne "${c1}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬${c3} (100%) \r"
sleep 0.5
if [ -d '/storage/emulated/0/WhatsApp/Media/.Statuses' ];then
cd /storage/emulated/0/WhatsApp/Media/.Statuses/
cp -rf * /sdcard/DCIM/WA-STATUS
echo -ne '\033[1m[√] Files Saved Dir : emulated/0/DCIM/WA-STATUS\r'
echo -e "\n" ;fi
NORM
###>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
